version: '2'

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile-server
    command: bundle exec ruby server.rb
    volumes:
      - ./server:/fortune-server
    expose:
      - '1983'

  client:
    build:
      context: .
      dockerfile: Dockerfile-client
    command: bundle exec rails server --binding 0.0.0.0 --port 3000
    volumes:
      - ./client:/fortune-client
    ports:
      - '3000:3000'
    links:
      - server
